// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entities.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveEntity = `-- name: ArchiveEntity :exec
SELECT core_archive_entity($1)
`

func (q *Queries) ArchiveEntity(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveEntity, argUuid)
	return err
}

const createEntity = `-- name: CreateEntity :one
SELECT id, uuid, fundamental_type_id, created_at, updated_at, archived_at, owner_id
FROM core_create_entity($1)
`

func (q *Queries) CreateEntity(ctx context.Context, fundamentalTypeID int64) (Entity, error) {
	row := q.db.QueryRow(ctx, createEntity, fundamentalTypeID)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FundamentalTypeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.OwnerID,
	)
	return i, err
}

const createEntityWithOwner = `-- name: CreateEntityWithOwner :one
SELECT id, uuid, fundamental_type_id, created_at, updated_at, archived_at, owner_id
FROM core_create_entity_with_owner($1, $2)
`

type CreateEntityWithOwnerParams struct {
	FundamentalTypeID int64       `json:"fundamental_type_id"`
	OwnerID           pgtype.Int8 `json:"owner_id"`
}

func (q *Queries) CreateEntityWithOwner(ctx context.Context, arg CreateEntityWithOwnerParams) (Entity, error) {
	row := q.db.QueryRow(ctx, createEntityWithOwner, arg.FundamentalTypeID, arg.OwnerID)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FundamentalTypeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.OwnerID,
	)
	return i, err
}

const getEntityByID = `-- name: GetEntityByID :one
SELECT
  e.id, e.uuid, e.fundamental_type_id,
  t.slug AS fundamental_type_slug,
  e.created_at, e.updated_at, e.archived_at
FROM entities e
JOIN types t ON e.fundamental_type_id = t.id
WHERE e.id = $1
`

type GetEntityByIDRow struct {
	ID                  int64              `json:"id"`
	Uuid                uuid.UUID          `json:"uuid"`
	FundamentalTypeID   int64              `json:"fundamental_type_id"`
	FundamentalTypeSlug string             `json:"fundamental_type_slug"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt          *time.Time         `json:"archived_at"`
}

func (q *Queries) GetEntityByID(ctx context.Context, id int64) (GetEntityByIDRow, error) {
	row := q.db.QueryRow(ctx, getEntityByID, id)
	var i GetEntityByIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FundamentalTypeID,
		&i.FundamentalTypeSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getEntityByUUID = `-- name: GetEntityByUUID :one
SELECT
  e.id, e.uuid, e.fundamental_type_id,
  t.slug AS fundamental_type_slug,
  e.created_at, e.updated_at, e.archived_at
FROM entities e
JOIN types t ON e.fundamental_type_id = t.id
WHERE e.uuid = $1
`

type GetEntityByUUIDRow struct {
	ID                  int64              `json:"id"`
	Uuid                uuid.UUID          `json:"uuid"`
	FundamentalTypeID   int64              `json:"fundamental_type_id"`
	FundamentalTypeSlug string             `json:"fundamental_type_slug"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt          *time.Time         `json:"archived_at"`
}

func (q *Queries) GetEntityByUUID(ctx context.Context, argUuid uuid.UUID) (GetEntityByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getEntityByUUID, argUuid)
	var i GetEntityByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FundamentalTypeID,
		&i.FundamentalTypeSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const unarchiveEntity = `-- name: UnarchiveEntity :exec
SELECT core_unarchive_entity($1)
`

func (q *Queries) UnarchiveEntity(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, unarchiveEntity, argUuid)
	return err
}
